platform :ios, '11.3'
use_frameworks!

target 'AntViewer_ios_Example' do
  pod 'AntViewer_ios', :path => '../'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

  target 'AntViewer_ios_Tests' do
    inherit! :search_paths

    
  end
end
